services:
  # mongo:
  #   image: mongo:7
  #   restart: unless-stopped
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    # environment:
    #   MONGODB_URI: mongodb://mongo:27017/inventory_management
    # depends_on:
    #   - mongo

# volumes:
#   mongo_data:
